package(default_visibility = ["//visibility:public"])

filegroup(
    name = "headers",
    srcs = [
        "client.h",
        "config.h",
        "log.h",
        "server.h",
        "sys_arduino.h",
        "sys_esp32.h",
        "sys_unix.h",
        "sys_win32.h",
        "sys.h",
        "tp.h",
        "uds.h",
        "util.h",
        "//src:version.h",
        "tp/isotp_c_socketcan.h",
        "tp/isotp_c.h",
        "tp/isotp_mock.h",
        "tp/isotp_sock.h",
        "tp/isotp-c/isotp_config.h",
        "tp/isotp-c/isotp_defines.h",
        "tp/isotp-c/isotp_user.h",
        "tp/isotp-c/isotp.h",
    ]
)
